import { action, observable } from "mobx";

class LayoutStore {
    @observable data = []

    @action.bound getData(){
        this.data = [
            {
                pro_name:'威胁情报融合平台',
                pro_bg:'广东那边的演示',
                pro_address:'10.10.1.53:18080/threat',
                deploy_address:'10.10.1.53:22',
                deploy_list:'var/tilsp/www/threat',
                code_branch:'guangdong',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/linkage.git',
                update_date:'2020-09-27',
                upload_user:'王庆红',
                respon_user:'王善标' 
            },
            {
                pro_name:'融合联动平台北京节点（目前作为演示环境）',
                pro_bg:'北京节点',
                pro_address:'10.10.1.53:18080/linkage',
                deploy_address:'10.10.1.53:22',
                deploy_list:'var/tilsp/www/linkage',
                code_branch:'beijing',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/linkage.git',
                update_date:'2021-03-02',
                upload_user:'王庆红',
                respon_user:'王善标' 
            },
            {
                pro_name:'融合联动4院演示',
                pro_bg:'4院',
                pro_address:'10.10.1.53:18080/online/',
                deploy_address:'10.10.1.53:22',
                deploy_list:'var/tilsp/www/online',
                code_branch:'4ground',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/linkage.git',
                update_date:'2020-10-16',
                upload_user:'王庆红',
                respon_user:'王千寻' 
            },
            {
                pro_name:'融合联动平台深圳节点',
                pro_bg:'广东那边的演示',
                pro_address:'10.10.1.54:18080/linkage',
                deploy_address:'10.10.1.54:22',
                deploy_list:'var/tilsp/www/linkage',
                code_branch:'shenzhen',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/linkage.git',
                update_date:'2021-05-04',
                upload_user:'杨玲',
                respon_user:'王善标' 
            },
            {
                pro_name:'Tisrs',
                pro_bg:'内⽹python环境',
                pro_address:'10.10.1.52:18080/tisrsui/',
                deploy_address:'10.10.1.52:22',
                deploy_list:'var/tisrs/www/tisrsui',
                code_branch:'dev',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/tisrs.git',
                update_date:'2021-03-05',
                upload_user:'王庆红',
                respon_user:'王善标' 
            },
            {
                pro_name:'Tisrs',
                pro_bg:'公⽹python环境',
                pro_address:'101.254.236.76:14281/tisrsui',
                deploy_address:'101.254.236.76:14222',
                deploy_list:'var/tisrs_py/www/tisrsui',
                code_branch:'dev',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/tisrs.git',
                update_date:'2021-03-05',
                upload_user:'许红梅',
                respon_user:'王善标' 
            },
            {
                pro_name:'Tisrs',
                pro_bg:' C语⾔环境',
                pro_address:'101.254.236.76:14281/tisrs',
                deploy_address:'101.254.236.76:14222',
                deploy_list:'var/tisrs/www/tisrs',
                code_branch:'C_language',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/tisrs.git',
                update_date:'2020-10-09',
                upload_user:'王庆红',
                respon_user:'王善标' 
            },
            {
                pro_name:'流影',
                pro_bg:'实验版',
                pro_address:'101.254.236.75:13380/ver0.9/',
                deploy_address:'101.254.236.75:13322',
                deploy_list:'var/www/html/ver0.9',
                code_branch:'dev',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/shadowflow_react.git',
                update_date:'2021-02-05',
                upload_user:'王庆红',
                respon_user:'王德威' 
            },
            {
                pro_name:'流影',
                pro_bg:'实验版(⼤流量、固态盘)',
                pro_address:'101.254.236.76:11380/ver0.9/',
                deploy_address:'101.254.236.76:11322',
                deploy_list:'Server/www/html/ver0.9',
                code_branch:'Copy 实验版',
                code_repo:'Copy 实验版',
                update_date:'2021-01-11',
                upload_user:'满方辉',
                respon_user:'王德威' 
            },
            {
                pro_name:'流影',
                pro_bg:'标准版',
                pro_address:'101.254.236.75:13380/new/std/',
                deploy_address:'101.2454.236.75:13322',
                deploy_list:'var/www/html/new/std',
                code_branch:'master',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/shadowflow_std.git',
                update_date:'2021-08-19',
                upload_user:'杨玲',
                respon_user:'王德威' 
            },
            {
                pro_name:'威胁情报融合平台',
                pro_bg:'广东那边的演示',
                pro_address:'10.10.1.53:18080/threat',
                deploy_address:'10.10.1.53:22',
                deploy_list:'var/tilsp/www/threat',
                code_branch:'guangdong',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/linkage.git',
                update_date:'2020-09-27',
                upload_user:'王庆红',
                respon_user:'王善标' 
            },
            {
                pro_name:'流影',
                pro_bg:'资产版',
                pro_address:'101.254.236.75:13380/new/asset/',
                deploy_address:'101.2454.236.75:13322',
                deploy_list:'var/www/html/new/asset',
                code_branch:'master',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/shadowflow_asset.git',
                update_date:'2020-12-23',
                upload_user:'王庆红',
                respon_user:'王善标' 
            },
            {
                pro_name:'流云',
                pro_bg:'测试版',
                pro_address:'101.254.236.75:13380/tiui/',
                deploy_address:'',
                deploy_list:'',
                code_branch:'',
                code_repo:'',
                update_date:'',
                upload_user:'',
                respon_user:'' 
            },
            {
                pro_name:'NTMS',
                pro_bg:' 外⽹环境',
                pro_address:'101.254.236.76:14580/ntmsui/',
                deploy_address:'101.254.236.76:14522',
                deploy_list:'/var/ntms/www/ntmsui',
                code_branch:'master',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/ntms.git',
                update_date:'2021-02-25',
                upload_user:'许红梅',
                respon_user:'王善标' 
            },
            {
                pro_name:'NTMS',
                pro_bg:' 内⽹环境',
                pro_address:'10.10.1.52:18081/ntmsui/',
                deploy_address:'10.10.1.53:22',
                deploy_list:'var/rule/www/ntmsui',
                code_branch:'master',
                code_repo:'ssh://git@101.254.236.76:16022/home/gitrepo/front/ntms.git',
                update_date:'2021-08-09',
                upload_user:'杨玲',
                respon_user:'王善标' 
            },
        ]
    }
}

export default new LayoutStore()